theory SquareProblem
imports Complex_Main "HOL-Analysis.Euclidean_Space"
begin
locale square_problem =
  fixes A B C D :: "real^2" 
  assumes square_ABCD: "orthogonal (B - A) (C - B)" 
    and "orthogonal (C - B) (D - C)"
    and "orthogonal (D - C) (A - D)"
    and "orthogonal (A - D) (B - A)"
    and "norm (B - A) = norm (C - B)"
    and "norm (C - B) = norm (D - C)"
    and "norm (D - C) = norm (A - D)"
  fixes E :: "real^2"
  defines "E ≡ (A + D) / 2"
  fixes F G H J :: "real^2"
  assumes F_on_CE: "∃t∈{0..1}. F = (1 - t) •R C + t •R E"
    and G_on_CE: "∃t∈{0..1}. G = (1 - t) •R C + t •R E"
    and H_on_AB: "∃t∈{0..1}. H = (1 - t) •R A + t •R B"
    and J_on_BC: "∃t∈{0..1}. J = (1 - t) •R B + t •R C"
    and square_FGHJ: "orthogonal (G - F) (H - G)" 
    and "orthogonal (H - G) (J - H)"
    and "orthogonal (J - H) (F - J)"
    and "orthogonal (F - J) (G - F)"
    and "norm (G - F) = norm (H - G)"
    and "norm (H - G) = norm (J - H)"
    and "norm (J - H) = norm (F - J)"
  fixes K L M N :: "real^2"
  assumes K_on_GH: "∃t∈{0..1}. K = (1 - t) •R G + t •R H"
    and L_on_GH: "∃t∈{0..1}. L = (1 - t) •R G + t •R H"
    and M_on_AD: "∃t∈{0..1}. M = (1 - t) •R A + t •R D"
    and N_on_AB: "∃t∈{0..1}. N = (1 - t) •R A + t •R B"
    and square_KLMN: "orthogonal (L - K) (M - L)" 
    and "orthogonal (M - L) (N - M)"
    and "orthogonal (N - M) (K - N)"
    and "orthogonal (K - N) (L - K)"
    and "norm (L - K) = norm (M - L)"
    and "norm (M - L) = norm (N - M)"
    and "norm (N - M) = norm (K - N)"
    and area_KLMN: "norm (L - K) * norm (M - L) = 99"
  fixes area_FGHJ :: real
  defines "area_FGHJ ≡ norm (G - F) * norm (H - G)"
  